name: Build Package on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Extract package version
        id: extract_version
        run: |
          echo ::set-output name=VERSION::$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
        
      - name: Set package version
        run: |
          sed -i -e "s/version = \".*\"/version = \"$VERSION\"/g" pyproject.toml

      - name: Commit changes
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
          git commit -a -m "Update package version to $VERSION" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Build and Publish to TestPyPI
        uses: docker://python:3.9-buster
        with:
          entrypoint: /bin/sh
          args: -c "pip install -U pip && pip install build twine && python -m build --outdir dist && python -m twine upload --repository testpypi --skip-existing dist/*"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
